name: Corellium

on: [push]

jobs:
  corellium:
    runs-on: ubuntu-latest
    steps:
      
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Corellium CLI
        run: npm install -g @corellium/corellium-cli

      - name: Install sshpass
        run: |
          sudo apt-get update
          sudo apt-get install -y sshpass
      
      - name: Login to Corellium
        run: corellium login --apitoken ${{ secrets.CORELLIUM_API_TOKEN }} --endpoint ${{ secrets.CORELLIUM_ENDPOINT }} --password ${{ secrets.CORELLIUM_LOGIN_PASSWORD }}

      - name: Create device
        run: |
          echo "Creating generic Linux instance..."

          id=$(corellium instance create server 24.4.2 ${{ secrets.CORELLIUM_PROJECT }} --name CI_CD_PIPELINE)
          echo "instanceId=$id" >> $GITHUB_ENV
          sleep 75

      - name: Get instance IP
        run: |
          jsonFormat=$(corellium instance get --i "${{ env.instanceId }}" --format json)

          ip=$(python3 -c '
          import json, sys
          print(json.load(sys.stdin)["wifiIp"])
          ' <<< "$jsonFormat")

          echo "instanceIP=$ip" >> "$GITHUB_ENV"

      - name: Setup SSH Key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519

          for i in {1..5}; do
            ssh-keyscan -H proxy.app.avh.corellium.com >> ~/.ssh/known_hosts && break
            echo "Retrying ssh-keyscan..."
            sleep 5
          done

      - name: Run Automation
        env:
          SSH_PROXY: ${{ secrets.SSH_PROXY }}
          VM_USER: ${{ secrets.VM_USER }}
          VM_PASSWORD: ${{ secrets.VM_PASSWORD }}
          DEPLOY_KEY_GITHUB: ${{ secrets.DEPLOY_KEY_GITHUB }}
          CORELLIUM_HOST: ${{ secrets.CORELLIUM_ENDPOINT }}
          CORELLIUM_TOKEN: ${{ secrets.CORELLIUM_API_TOKEN }}
          VM_IP: ${{ env.instanceIP }}
        run: |
          chmod +x .github/scripts/corellium_ci.sh
          ./.github/scripts/corellium_ci.sh

      - name: Stop device
        if: always()
        run: corellium instance stop ${{ env.instanceId }} true

      - name: Delete device
        if: always()
        run: |
          corellium instance delete ${{ env.instanceId }}

      - name: Logout
        if: always()
        run: |
          corellium logout
